version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: quanlyhs_db
    restart: always
    environment:
      POSTGRES_USER: eduadmin
      POSTGRES_PASSWORD: edu@123456
      POSTGRES_DB: edumanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
