services:
  - type: web
    name: quanlyhs-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: DB_HOST
        value: db.bgyzjtwhnksijlxazjwe.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: postgres
      - key: DB_NAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 3001